### ISSUE TITLE
boxfile.ishared() don't work

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-android#263]
iam share a file to other user.

the boxfile.isShared() return false instead of true

**Comment by L-Henke** [comment]
You might be using it wrong, because I think this test should include all the cases isShared() should work for. https://github.com/Qabel/qabel-android/blob/master/qabelbox/src/androidTest/java/de/qabel/qabelbox/storage/BoxTest.java#L280 and it only is useful for a very limited case which is documented in the Javadoc https://github.com/Qabel/qabel-android/blob/master/qabelbox/src/main/java/de/qabel/qabelbox/storage/BoxFile.java#L72. If you would describe the case where this doesn't work for, I can try to fix it.

**Comment by dannywerner** [comment]
my error. iam added nav.commit after creating metadata and all fine

**Comment by audax** [comment]
Resolved by #274
