### ISSUE TITLE
Apply wording issues mentioned in merged PR 

### ISSUE THREAD

**Issue by roeslpa** [Qabel/qabel-android#282]
Please apply or discuss wording issues mentioned in #281

**Comment by jasinai** [comment]
I will correct the translations as far as I am sure about them.

**Comment by jasinai** [comment]
We have to discuss this:
* [Do not know whether we want to use abbreviations, but if not, please use do not..](https://github.com/Qabel/qabel-android/pull/281/files#r54546048)
* [I am in favor of using either always "E-Mail" or always "E-Mail Adresse".. ](https://github.com/Qabel/qabel-android/pull/281/files#r54543344)
* [If this is used for explaining the drop ID generation, I would propose to focus on more needed traffic instead of energy consumption. ](https://github.com/Qabel/qabel-android/pull/281/files#r54543784)

**Comment by roeslpa** [comment]
1. Decision should be made by marketing..
2. I do not mind which expression is used but only one should be used
3. Since mobile devices can be charged but traffic is restricted, I highly recommend to stress this point instead of the energy consumption (I actually do not know where this comes from?!)
