### ISSUE TITLE
Contact import does not work

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#315]
Two Tester have problems during contact import, please try to reproduce this behavior and if needed fix the problem.

Comments:
someone sent me contacts via qabel chat in the app . I have it stored in the incoming shares and wanted to import them . Import failed.

.qco files can not be opened via the operating system in Qabel of the downloads from

**Comment by L-Henke** [comment]
After searching the original bug reports, because I couldn't figure out the point in the translated reports, I assume that this isn't really a bug but a missing feature. Of course we can import contacts via our import function, but we have not registered the App to handle .qco files. 

A completely new import dialog would be required for this use case, because you would have to select the identity you want to import the contact to after clicking on the .qco file from an other app.

**Comment by wischweh** [comment]
I already worked on this and fixed some things. (Integration pending). If you give me the .qco which does not work i can check if it is already fixed
