### ISSUE TITLE
make jenkins stable for android

### ISSUE THREAD

**Issue by hash13** [Qabel/qabel-android#400]
check if all adb commands correct execute
e.g.
adb uninstall de.qabel.qabel return Success

and if devices successfully connected
(create self repair scripts like adb kill-server.... adb reboot ....)

**Comment by jmt85** [comment]
is the issue still relevant?

**Comment by wischweh** [comment]
yes, still relevant

**Comment by dannywerner** [comment]
yes, it probably has a reason when I create a ticket. the issues slowing our daily work

**Comment by dannywerner** [comment]
additional add performance boosts like:
./gradlew --daemon --parallel 
instead of 
./gradlew

more infos at: 
http://jimulabs.com/2014/10/speeding-gradle-builds/
https://medium.com/@erikhellman/boosting-the-performance-for-gradle-in-your-android-projects-6d5f9e4580b6

maybe the latest 64 bit java can compile faster?

**Comment by dannywerner** [comment]
add watchdog if build(tests) hangs (currently a android gradle build can hang many hours)

**Comment by dannywerner** [comment]
if iam stop a running jenkins task... iam suppose that the tests running still at devices, but should stop
