### ISSUE TITLE
Client shuts down during "share file"

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#558]
When i select a file and share it to another contact the android client gets killed - reproducable...
When i restart the client and i go to the file it shows "shared to other people" and i can unshare it but it doesn't appear in contact conversation history - so i am not sure it got really shared

**Comment by audax** [comment]
And here is the crash log:
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'de.qabel.core.drop.DropMessage de.qabel.qabelbox.chat.ChatServer.createShareDropMessage(de.qabel.core.config.Identity, java.lang.String, java.lang.String, java.lang.String)' on a null object reference `

The funny part is that the method is actually static.

**Comment by jmt85** [comment]
see #565
