### ISSUE TITLE
Default upload folder

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#793]
I want to specify a default upload folder. That default folder should be used for uploads of photographs directly from chat and as a default for uploads via intents.

**Comment by thechauffeur** [comment]
After a discussion with @audax. This issue is now only about defining a default folder which the user **cannot** change. This default folder will be named `Upload` and **not** translated.

For the issues which depend on this default folder there are important things to handle.
 * If the upload is automatic and the default folder doesn't exist: Create it.
 * If the upload is not automatic but the default folder should be shown by default:
  * If the default folder doesn't exist: Show Root.
  * Otherwise: Show the default folder.

The user may rename the default folder using his remote file browser. This is not handled in any special way. E.g. the next time an automatic upload occurs -- using the default upload folder -- a new `Upload` folder must be created (see rules above).
